name: On version tag

on:
  workflow_dispatch:
  push:
    tags:
      - v* # Push events matching v*, e.g. v2.0.0.

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
    - name: Checkout
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        context: Frontend
        tags: collaction/frontend:${{ steps.get_version.outputs.VERSION }}
        push: true

  build_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
    - name: Checkout
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        file: CollAction/Dockerfile
        context: .
        tags: collaction/backend:${{ steps.get_version.outputs.VERSION }}
        dockerfile: CollAction/Dockerfile
        push: true
